services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        VITE_ISAAC_SIM_SERVER: ${ISAAC_SIM_HOST}
        VITE_ISAAC_SIM_SIGNAL_PORT: ${ISAAC_SIGNAL_PORT:-49100}
        VITE_ISAAC_SIM_MEDIA_PORT: ${ISAAC_MEDIA_PORT:-47998}
        VITE_FORCE_WSS: "false"
    ports:
      - "5555:80"
    restart: unless-stopped
